
complement = { "A": "T",
               "T": "A",
               "C": "G",
               "G": "C"}

str1 = "TATGGTGTACAGCGAGCGTTCCAGGCAGCAAGCCTATACCGTGGGTCTTGGGCGAAATGTTTGCGTCGCGCAGGTGTGCTTACACGATTTAACCGTAACAGTTTTTGTACAACTATAGCGACACCTGATGTCCACGTCGTTGAAAAACATACCTAACATTAACCTAACCTAGTCCACGTATTTGAATTTTTCATGGAGCCTCCATACAGCGAACCCAGAAAGCACATACATGGTAGTACGGCCGAGTCGAACCGCTATCGCGCGGGAAGGGTATTAATGAGTGGGGGGAGCCAGGTCGTGGAGGGAGTTAATATCCAGCACGATTTTTTCAACTCATGAATCTTTAGTGACCCTGGTAACAGTGTACTCGTTCGCCCCAGCCTAACTACACAAGAGACCAATCTTGGTCAGCCTAGAGCCGGAATCATGGAGCGTTTCGAGCTAGCGGTCTCCGGGTGCGAAGTACCCAGGGCAAAACACCCTTCAAGCAACTATTAGCCTAGGCCCACGTTAACGGTGTAGAGCAAATATGGACCCTGAGATTACAACAAGTTGTCTGGGCGTAACCGGACCGGAAAAAAGGGCAGCGGATAGCCAACGGCTAAAGTGGACGCAATTTCTGTCGGAACAGTGGTTCTCCGCGGAGCGAACAGTTCTCTGTATCAGTATATGTTCAGATGACGCCTTAGTCGACCGCCACACGACTTAGAAGCCTATACGGGCACCAGGACCATCGAACAGGGCGGATCGCACGACACTCGACACGATGACCGCGCATCGGGGCGCCGCACTGGACAACAGACCCGAAATTTTCTAGGCTCATGGGCGCCTACATCAGAAAGATGAAGTGTGTAGCGGACAGCTCATTAACATAGGATACCAACAACTGCTCAGGGACTCGTAGGTTAAG"
str1 = str1[::-1]

output = ""
for char in str1:
    output += complement[char]

print(output)